language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2

env:
  - RAILS=4.0.0
  - RAILS=3.2.0
  - RAILS=3.1.0


services: postgresql
before_script:
  - psql -c 'create database pg_search_scope_test;' -U postgres